config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'home#index'

  authenticated :user do
    root 'categories#index', as: :authenticated_root
  end

  resources :categories do
    resources :transactions, only: %i[new create index destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :transactions, dependent: :destroy
  belongs_to :user

  validates :name, presence: true, length: { maximum: 30 }
  validates :icon, presence: true

  def total_amount
    transactions.sum(:amount)
  end
end

app/models/category_transaction.rb
class CategoryTransaction < ApplicationRecord
end

app/models/transaction.rb
class Transaction < ApplicationRecord
  belongs_to :author, class_name: 'User'

  belongs_to :category
  validates :name, presence: true
  validates :amount, presence: true
  validates :category, presence: true
  validate :belongs_to_a_category

  def belongs_to_a_category
    errors.add(:category_id, 'must belong to a category') unless category_id && category
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :transactions, foreign_key: 'author_id'

  has_many :categories, dependent: :destroy

  validates :name, presence: true
  validates :email, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_user!

  def index
    @categories = current_user.categories.includes(:transactions)
  end

  def new
    @category = Category.new
  end

  def create
    @category = current_user.categories.build(category_params)

    if @category.save
      redirect_to categories_path, notice: 'Category was successfully created.'
    else
      render :new
    end
  end

  def destroy
    @category = current_user.categories.find(params[:id])
    @category.destroy
    redirect_to categories_path, notice: 'Category was successfully deleted.'
  end

  def transactions
    @category = current_user.categories.find(params[:category_id])
    @transactions = @category.transactions.order(date: :desc)
    @total_amount = @transactions.sum(:amount)

    render :index, locals: { transactions: @transactions, total_amount: @total_amount }
  end

  private

  def category_params
    params.require(:category).permit(:name, :icon)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @categories = current_user.categories if user_signed_in?
    redirect_to categories_path if user_signed_in?
  end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_category

  def index
    @transactions = @category.transactions.order(created_at: :desc)
    @total_amount = @transactions.sum(:amount)
  end

  def new
    @category = Category.find(params[:category_id])
    @categories = current_user.categories
    @transaction = Transaction.new
  end

  def create
    @transaction = @category.transactions.build(transaction_params)
    @transaction.author = current_user
    @transaction.date = Date.parse(params[:transaction][:date]) unless params[:transaction][:date].nil?

    if @transaction.save
      flash[:success] = "You've just added a new expense."

      # Fetch the transactions again after creating the new one
      @transactions = @category.transactions.order(created_at: :desc)

      redirect_to category_transactions_path(@category)
    else
      flash.now[:error] = @transaction.errors.full_messages.first
      render :new
    end
  end

  def destroy
    @transaction = Transaction.find(params[:id])
    @transaction.destroy
    flash[:success] = 'Expense item has been removed.'
    redirect_to category_transactions_path(@category)
  end

  private

  def set_category
    @category = current_user.categories.find(params[:category_id])
  end

  def transaction_params
    params.require(:transaction).permit(:name, :amount, :category_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/home_controller.rb
module HomeHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/categories/index.html.erb
<section class="container">
<div class="header">
  <%= link_to "<i class='fas fa-arrow-left'></i>".html_safe, :back, class: "back" %>
  <h1>Categories</h1>
  <%= form_for(current_user, url: destroy_user_session_path, method: :delete, html: { class: "nav-link" }) do |f| %>
    <%= f.button type: :submit, class: "btn-logout" do %>
      <%= content_tag :i, "", class: "fa-solid fa-right-from-bracket" %>
    <% end %>
  <% end %>
</div>

<% if @categories.any? %>
  <ul class="categories">
    <% @categories.each do |category| %>
      <li class="category">
      <a href="<%= category_transactions_path(category) %>">
      <div class="info">
        <div class = "info-name">
            <% if category.icon.present? %>
<div>
                  <%= raw category.icon %>
    
</div>            <% end %>
            <h3><%= category.name %></h3>
        </div>
        <div class="info-amount">
            <p>$<%= category.transactions.collect(&:amount).sum %></p>
        </div>
    </div>
      </li>
      </a>
    <% end %>
  </ul>
  <button class="btn addNew"><%= link_to 'Add New', new_category_path %></button>
<% else %>
  <p class="msg">No categories found. Click the button below to add a new category.</p>
  <button class="btn addNew"><%= link_to 'Add New', new_category_path%></button>
<% end %>

</section>

app/views/categories/new.html.erb
<section class="container">
  <div class="header">
    <%= link_to "<i class='fas fa-arrow-left'></i>".html_safe, categories_path, class: "back" %>
    <h1>New Category</h1>
    <%= form_for(current_user, url: destroy_user_session_path, method: :delete, html: { class: "nav-link" }) do |f| %>
      <%= f.button type: :submit, class: "btn-logout" do %>
        <%= content_tag :i, "", class: "fa-solid fa-right-from-bracket" %>
      <% end %>
    <% end %>
  </div>
  <div class="cat-form">
    <%= form_for @category do |f| %>
      <div class="field">
        <%= f.label :name %><br>
        <%= f.text_field :name, required: true %>
      </div>
      <div class="field">
        <%= f.label :icon %><br>
        <%= f.select :icon, { "House": "🏤", "Health": "💊", "Food": "🍕", "clothes": "👕", "School": "📚", "Gym": "🏋️‍♂️" }%>
      </div>
      <div class="actions">
        <%= f.submit "Create Category" %> 
      </div>
    <% end %>
  </div>
  </section>

app/views/home/index.html.erb
<%= content_tag :section, class: "custom-section" do %>
    <% if user_signed_in? %>
      <%= "categories" %>
    <% else %>
      <%= content_tag :div, class: "custom-flex-container" do %>
        <%= content_tag :h1, "Welcome to BudgetApp", class: "Welcome"%>
        <%= content_tag :div, class: "custom-absolute-container" do %>
          <div><%= button_to "Log in", new_user_session_path, method: :get, class: "auth-button login-btn" %>
          <%= button_to "Sign up", new_user_registration_path, method: :get, class: "auth-button signup" %>
        <% end %>
      <% end %>
    <% end %>
  <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BudgetApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw==" crossorigin="anonymous" referrerpolicy="no-referrer" />

    <%= javascript_importmap_tags %>
  </head>

  <body>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/transactions/index.html.erb
<section class="container">
  <div class="header">
    <%= link_to "<i class='fas fa-arrow-left'></i>".html_safe, categories_path, class: "back" %>
    <h1>Details</h1>
    <%= form_for(current_user, url: destroy_user_session_path, method: :delete, html: { class: "nav-link" }) do |f| %>
      <%= f.button type: :submit, class: "btn-logout logoutBtn" do %>
        <%= content_tag :i, "", class: "fa-solid fa-right-from-bracket" %>
      <% end %>
    <% end %>
  </div>
  <div class="content">
    <h2>Transaction for <%= @category.name %></h2>
    <% if @transactions.any? %>
      <p class="total">Total Amount: $<%= sprintf('%.2f', @total_amount) %></p>
      <div>
        <% @transactions.each do |transaction| %>
          <ul class="transactions-card">
            <li>Name: <%= transaction.name %></li>
            <li>Amount: $<%= sprintf('%.2f', transaction.amount) %></li>
            <h3><%= button_to 'Delete', category_transaction_path(@category, transaction), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn-danger' %></h3>
          </ul>
        <% end %>
      </div>
      <button class="btn addNew"><%= link_to 'Add New', new_category_transaction_path(@category, @transaction) %></button>

    <% else %>
      <p class="msg">No transactions found.</p>
      <button class="btn addNew"><%= link_to 'Add New', new_category_transaction_path(@category, @transaction) %></button>
    <% end %>
  </div>
</section>

app/views/transactions/new.html.erb
<section class="container">
<div class="header">
<%= link_to "<i class='fas fa-arrow-left'></i>".html_safe,  categories_path, class: "back" %>
<h1>Add Transaction</h1>
<%= form_for(current_user, url: destroy_user_session_path, method: :delete, html: { class: "nav-link" }) do |f| %>
  <%= f.button type: :submit, class: "btn-logout" do %>
    <%= content_tag :i, "", class: "fa-solid fa-right-from-bracket" %>
  <% end %>
<% end %>

</div>
<div class="content">
<h2>New Transaction for <%= @category.name %></h2>
<div class="tran-form">

<%= form_with model: [@category, @transaction], local: true do |f| %>
  <% if @transaction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@transaction.errors.count, "error") %> prohibited this transaction from being saved:</h2>
      <ul>
        <% @transaction.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name, required: true %>
  </div>

  <div class="field">
    <%= f.label :amount %>
    <%= f.text_field :amount, required: true %>
  </div>
  
<div class="field">
  <%= f.label :category_id %>
  <%= f.select :category_id, options_for_select((@categories&.collect { |c| [c.name, c.id] } || []), @category.id), {}, required: true %>
</div>

  <div class="actions">
    <%= f.submit "Create transaction", class: "btn btn-primary" %>
  </div>
  </div>
<% end %>
</div>
</section>